artifact_location: /Users/venkatapraneethcheturi/Downloads/neuralforge/backend/mlflow_artifacts/751758799069790706
creation_time: 1781788592207
effective_trace_archival_retention: null
experiment_id: '751758799069790706'
last_update_time: 1781788592207
lifecycle_stage: active
name: neuralforge
trace_location: null
workspace: default
